name: Build and Publish InSpec to GitHub Packages

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish to GitHub Packages'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

env:
  RUBY_VERSION: '3.1'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout InSpec repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: false
      
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      
      - name: Build gems
        run: |
          echo "Building InSpec gems..."
          gem build inspec-core.gemspec
          gem build inspec.gemspec
          
          # Build inspec-bin from its own directory
          cd inspec-bin
          gem build inspec-bin.gemspec
          mv *.gem ../
          cd ..
          
          # List built gems
          ls -la *.gem
      
      - name: Run basic tests
        run: |
          echo "Running basic smoke tests..."
          bundle exec rake test:isolated
        continue-on-error: true
      
      - name: Configure RubyGems credentials
        if: github.event_name == 'push' || github.event.inputs.publish == 'true'
        run: |
          mkdir -p ~/.gem
          echo ":github: Bearer ${{ secrets.GITHUB_TOKEN }}" > ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
      
      - name: Publish to GitHub Packages
        if: github.event_name == 'push' || github.event.inputs.publish == 'true'
        run: |
          # Get the owner name in lowercase (GitHub Packages requires lowercase)
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          
          echo "Publishing to GitHub Packages for owner: ${OWNER}"
          
          # Publish each gem
          for gem in *.gem; do
            echo "Publishing ${gem}..."
            gem push --key github \
              --host "https://rubygems.pkg.github.com/${OWNER}" \
              "${gem}" || echo "Failed to publish ${gem}, continuing..."
          done
      
      - name: Upload gems as artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: inspec-gems
          path: |
            *.gem
          retention-days: 7
      
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.gem
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-installation:
    needs: build
    if: github.event_name == 'push' || github.event.inputs.publish == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    
    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      
      - name: Wait for package to be available
        run: sleep 30
      
      - name: Test gem installation
        run: |
          # Configure gem sources
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          
          # Create test Gemfile
          cat > Gemfile << EOF
          source "https://rubygems.org"
          source "https://rubygems.pkg.github.com/${OWNER}" do
            gem "inspec-core"
          end
          EOF
          
          # Install
          bundle config set --local https://rubygems.pkg.github.com/${OWNER} ${{ secrets.GITHUB_TOKEN }}
          bundle install
          
          # Test that it works
          bundle exec ruby -e "require 'inspec'; puts 'InSpec version: ' + Inspec::VERSION"